import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import AuthProvider from "@/components/providers/AuthProvider";

// Carregando a fonte Inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased p-8 flex flex-col gap-8`} id="root">
        <Header />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
